# GCP Deployment Configuration for SQL Retriever
# Update these values before deployment

# Project Configuration
project_id: "heroic-overview-466605-p6"  # Your actual GCP project ID
region: "us-central1"
zone: "us-central1-a"

# Cloud Storage Configuration
bucket_name: "sql-retriever-storage-heroic-overview"  # Must be globally unique
bucket_class: "STANDARD"

# Cloud SQL Configuration
sql_instance_name: "sql-retriever-db"
sql_database_name: "crm_database"
sql_user: "sql_retriever_user"
sql_password: "SecurePass123!"  # Change this to a secure password
sql_tier: "db-f1-micro"  # For cost optimization, upgrade for production

# Artifact Registry Configuration
registry_name: "sql-retriever-registry"
image_name: "sql-retriever-api"

# Cloud Run Configuration
service_name: "sql-retriever-api"
service_memory: "2Gi"
service_cpu: "1000m"
service_min_instances: 0
service_max_instances: 10
service_timeout: "300s"

# Environment Variables
api_key: "sk-sqlret-2024-prod-key-secure-random-123456789"  # Secure API key
model_name: "unsloth/Llama-3.2-3B-Instruct"
log_level: "INFO"
environment: "production"

# Runpod Integration (Optional)
# If using external model hosting service like Runpod
model_endpoint: "your_runpod_endpoint_here"  # Format: https://api.runpod.ai/v2/YOUR_ENDPOINT_ID
runpod_api_key: "your_runpod_api_key_here"  # If using Runpod authentication
model_provider: "local"  # Options: local, runpod, openai, anthropic
inference_timeout: 120  # Timeout in seconds for model inference

# Secret Manager Configuration (Recommended for Production)
use_secret_manager: false  # Set to true to store secrets in Google Secret Manager
secret_names:
  api_key: "sql-retriever-api-key"
  sql_password: "sql-retriever-sql-password"
  runpod_api_key: "sql-retriever-runpod-key"  # Only used if model_provider is "runpod"
  openai_api_key: "sql-retriever-openai-key"  # Only used if model_provider is "openai"

# Cost Settings
enable_cost_monitoring: true
daily_spend_limit: 50  # USD
cost_alert_emails:
  - "admin@yourdomain.com"  # Add your email for cost alerts
monthly_budget_limit: 100  # USD - hard limit for monthly spend

# Security Settings
enable_cloud_armor: false  # Set to true for production DDoS protection
allowed_origins: "*"  # Restrict for production (e.g., "https://yourdomain.com")
enable_cors: true
cors_methods: "GET,POST,PUT,DELETE,OPTIONS"
enable_rate_limiting: true
rate_limit_requests_per_minute: 100

# Backup Configuration
enable_automated_backups: true
backup_retention_days: 7
backup_schedule: "0 2 * * *"  # Daily at 2 AM UTC

# Monitoring Configuration
enable_detailed_monitoring: true
log_retention_days: 30
enable_performance_insights: true
alert_thresholds:
  cpu_utilization: 80  # Percent
  memory_utilization: 85  # Percent
  error_rate: 5  # Percent
  response_time: 5000  # Milliseconds

# Scaling Configuration
auto_scaling:
  enable: true
  target_cpu_utilization: 70  # Percent
  target_memory_utilization: 75  # Percent
  min_instances: 0
  max_instances: 10
  scale_up_cooldown: 60  # Seconds
  scale_down_cooldown: 300  # Seconds

# Network Configuration (Advanced)
vpc_connector: ""  # Leave empty to use default network
enable_private_ip: false  # Use private IP for Cloud SQL connection
authorized_networks: []  # List of IP ranges allowed to access Cloud SQL

# Development/Testing Settings
enable_debug_mode: false  # Enable for development environments
mock_external_services: false  # Use for testing without external dependencies
test_data_seed: true  # Populate database with test data 