# GCP Deployment Configuration for SQL Retriever
# Update these values before deployment

# Project Configuration
project_id: "heroic-overview-466605-p6"
region: "us-central1"
zone: "us-central1-a"

# Cloud Storage Configuration
bucket_name: "sql-retriever-storage-heroic-overview"
bucket_class: "STANDARD"

# Cloud SQL Configuration
sql_instance_name: "sql-retriever-db"
sql_database_name: "crm_database"
sql_user: "sql_retriever_user"
sql_password: "SecurePass123!"
sql_tier: "db-f1-micro"

# Artifact Registry Configuration
registry_name: "sql-retriever-registry"
image_name: "sql-retriever-api"

# Cloud Run Configuration
service_name: "sql-retriever-api"
service_memory: "1Gi"
service_cpu: "1000m"
service_min_instances: 0
service_max_instances: 10
service_timeout: "300s"

# Environment Variables
api_key: "sk-sqlret-2024-prod-key-secure-random-123456789"
model_name: "unsloth/Llama-3.2-3B-Instruct"
log_level: "INFO"
environment: "production"

# Runpod Integration (Optional)
# If using external model hosting service like Runpod
model_endpoint: "your_runpod_endpoint_here"
runpod_api_key: "your_runpod_api_key_here"
model_provider: "local"
inference_timeout: 120

# Secret Manager Configuration (Recommended for Production)
use_secret_manager: false
secret_names:
  api_key: "sql-retriever-api-key"
  sql_password: "sql-retriever-sql-password"
  runpod_api_key: "sql-retriever-runpod-key"
  openai_api_key: "sql-retriever-openai-key"

# Cost Settings
enable_cost_monitoring: true
daily_spend_limit: 50
cost_alert_emails:
  - "admin@yourdomain.com"
monthly_budget_limit: 100

# Security Settings
enable_cloud_armor: false
allowed_origins: "*"
enable_cors: true
cors_methods: "GET,POST,PUT,DELETE,OPTIONS"
enable_rate_limiting: true
rate_limit_requests_per_minute: 100

# Backup Configuration
enable_automated_backups: true
backup_retention_days: 7
backup_schedule: "0 2 * * *"

# Monitoring Configuration
enable_detailed_monitoring: true
log_retention_days: 30
enable_performance_insights: true
alert_thresholds:
  cpu_utilization: 80
  memory_utilization: 85
  error_rate: 5
  response_time: 5000

# Scaling Configuration
auto_scaling:
  enable: true
  target_cpu_utilization: 70
  target_memory_utilization: 75
  min_instances: 0
  max_instances: 10
  scale_up_cooldown: 60
  scale_down_cooldown: 300

# Network Configuration (Advanced)
vpc_connector: ""
enable_private_ip: false
authorized_networks: []

# Development/Testing Settings
enable_debug_mode: false
mock_external_services: false
test_data_seed: true